exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/mihirkelkar/website"

title: Mihir Kelkar
description: Personal Website for Mihir Kelkar
google_analytics: UA-155363190-1
